/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Daily */
        get: operations["report_daily_api_report_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Funnel */
        get: operations["report_funnel_api_report_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Detail */
        get: operations["company_detail_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Replies */
        get: operations["list_replies_api_replies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Costs */
        get: operations["costs_api_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedule Status */
        get: operations["schedule_status_api_schedule_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{nev}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Tail */
        get: operations["log_tail_api_logs__nev__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{company_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Approve */
        post: operations["review_approve_api_review__company_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{company_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Reject */
        post: operations["review_reject_api_review__company_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/suppressed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Suppressed */
        get: operations["review_suppressed_api_review_suppressed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financials/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Financials Worklist
         * @description A legjobb N lead, amirol meg nincs penzugyi adat -- CSV letoltes.
         *
         *     Mindig valid CSV-t ad vissza (ures listanal is csak a fejlecsor), hogy a
         *     letoltes soha ne akadjon el egy hianyzo fajlon.
         */
        get: operations["financials_worklist_api_financials_worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financials/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Financials Import
         * @description A kitoltott worklist (vagy csoportos beszamolo-export) feltoltese.
         *
         *     `dry` alapertelmezetten igaz (a repo altalanos dry-run-eloszor elve,
         *     CLAUDE.md Invariansok #1) -- a frontend elobb egy elonezetet mutat, a
         *     tenyleges iras kulon, kifejezett megerositessel tortenik.
         */
        post: operations["financials_import_api_financials_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/financials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Company Financials Save */
        post: operations["company_financials_save_api_companies__company_id__financials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Catalog */
        get: operations["job_catalog_api_jobs_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Current */
        get: operations["job_current_api_jobs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job History */
        get: operations["job_history_api_jobs_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Job Start
         * @description Elinditja a parancsot.
         *
         *     409, ha mar fut valami -- a futo job cimkejevel, hogy a felhasznalo lassa,
         *     MI fut (WEBUI-TERV.md F6). Az egyszerre-egy-futas indoka a jobs.py
         *     fejleceben all.
         */
        post: operations["job_start_api_jobs_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Job Cancel */
        post: operations["job_cancel_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Output */
        get: operations["job_output_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Stream
         * @description Elo naplo (SSE). Minden esemeny egy JSON: uj sorok + a job allapota.
         *
         *     A vegen egy utolso esemenyt kuldunk a lezart allapottal, majd lezarjuk a
         *     stremet -- igy a bongeszo `EventSource`-a nem kezd el ujracsatlakozni egy
         *     mar befejezett futasra.
         */
        get: operations["job_stream_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/send/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Preview
         * @description A mai terv teljes leveleivel, es egy 10 percig ervenyes token.
         *
         *     A TERV GUARDS NELKUL keszul. A `sender.py --dry` alapbol lefuttatja a
         *     guardsot, de az IMAP-ot nyit ES IR (DNC, bounce-naplo) -- egy elonezet
         *     nem irhat. A guards a kuldeskor fut le, es a tervet csak SZUKITENI tudja
         *     (aki kozben valaszolt vagy leiratkozott, kimarad). A felulet ezt kiirja.
         */
        post: operations["send_preview_api_send_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/send/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Live
         * @description ELES KULDES. Csak ervenyes, fel nem hasznalt, friss tokennel indul.
         *
         *     A sorrend nem cserelheto fel:
         *       1. ujra lekerdezzuk a tervet a kuldotol,
         *       2. a token ellenorzese ES elhasznalasa EGY lepesben (dupla kattintas),
         *       3. csak ezutan indul barmilyen folyamat.
         *
         *     Ha a 2. lepes elutasit, semmi nem indult el.
         */
        post: operations["send_live_api_send_live_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/send/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Sample
         * @description Mintalevel a SAJAT cimedre (`preview.py --send-to`).
         *
         *     VALODI SMTP-kuldes, de a valodi cimzettek nem kapnak semmit, es a
         *     `sent.csv` sem valtozik -- a lead szekvenciaja erintetlen marad.
         */
        post: operations["send_sample_api_send_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertsResponse */
        AlertsResponse: {
            /** Aktiv */
            aktiv: components["schemas"]["RiasztasSor"][];
            /** Lezart */
            lezart: components["schemas"]["RiasztasSor"][];
        };
        /** Body_financials_import_api_financials_import_post */
        Body_financials_import_api_financials_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Dry
             * @default true
             */
            dry: boolean;
        };
        /**
         * CompanyDetailResponse
         * @description A reszletes nezet. A sorok `select *`-gal jonnek (lasd a modul
         *     docstringjet), ezert a BURKOLO tipusos, a sorok mezoi nem.
         */
        CompanyDetailResponse: {
            /** Company */
            company: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Contacts */
            contacts: {
                [key: string]: unknown;
            }[];
            /** Opportunity Angles */
            opportunity_angles: {
                [key: string]: unknown;
            }[];
            /** Company Labels */
            company_labels: {
                [key: string]: unknown;
            }[];
            /** Outreach */
            outreach: {
                [key: string]: unknown;
            }[];
            /** Suppression */
            suppression: {
                [key: string]: unknown;
            }[];
        };
        /** CompanyFinancialsBody */
        CompanyFinancialsBody: {
            /** Revenue */
            revenue?: number | null;
            /** Headcount */
            headcount?: number | null;
            /** Financial Year */
            financial_year?: number | null;
            /**
             * Missing
             * @default false
             */
            missing: boolean;
        };
        /**
         * CompanyListItem
         * @description A lista-nezet oszlopai. Ezt a lekerdezes NEV SZERINT valasztja ki
         *     (nem `select *`), ezert itt teljes a modell.
         */
        CompanyListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string | null;
            /** Normalized Domain */
            normalized_domain: string | null;
            /** Status */
            status: string;
            /** Campaign */
            campaign: string | null;
            /** Economic Value */
            economic_value: string | null;
            /** Signal Score */
            signal_score: number | null;
            /** City */
            city: string | null;
            /** Industry */
            industry: string | null;
            /** Best Offer */
            best_offer: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Email */
            email: string | null;
        };
        /** CompanyListResponse */
        CompanyListResponse: {
            /** Items */
            items: components["schemas"]["CompanyListItem"][];
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** CostsResponse */
        CostsResponse: {
            /** Has Data */
            has_data: boolean;
            /** By Model */
            by_model: {
                [key: string]: components["schemas"]["ModellKoltseg"];
            };
            /** Total Usd */
            total_usd: number;
            /** First Ts */
            first_ts: string | null;
            /** Last Ts */
            last_ts: string | null;
        };
        /** DailyResponse */
        DailyResponse: {
            riasztasok: components["schemas"]["RiasztasBlokk"];
            sender: components["schemas"]["SenderAllapot"];
            /** Queued */
            queued: number;
            /** Ready */
            ready: number;
            /** Replied */
            replied: number;
            /** Review */
            review: number;
            /** Days Of Backlog */
            days_of_backlog: number | null;
        };
        /** DbAllapot */
        DbAllapot: {
            /** Ok */
            ok: boolean;
            /** Tablak */
            tablak: number;
        };
        /** EmailValidacio */
        EmailValidacio: {
            /** Mode */
            mode: string;
            /** Summary */
            summary: string;
        };
        /** EngineMeta */
        EngineMeta: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
            /** Aktiv */
            aktiv: boolean;
        };
        /** FinancialsImportResponse */
        FinancialsImportResponse: {
            /** Olvasott */
            olvasott: number;
            /** Frissitett */
            frissitett: number;
            /** Ures */
            ures: number;
            /** Hibas */
            hibas: number;
            /** Ismeretlen */
            ismeretlen: number;
            /** Ezer Forint Gyanu */
            ezer_forint_gyanu: string[];
            /** Ertekek */
            ertekek: {
                [key: string]: number;
            };
            /** Dry */
            dry: boolean;
        };
        /** FinancialsSaveResponse */
        FinancialsSaveResponse: {
            /** Economic Value */
            economic_value: string | null;
            /** Figyelmeztetes */
            figyelmeztetes: string | null;
        };
        /** FunnelResponse */
        FunnelResponse: {
            /** Companies Total */
            companies_total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Unknown Status */
            unknown_status: {
                [key: string]: number;
            };
            /** Contacts */
            contacts: {
                [key: string]: number;
            };
            email_validation: components["schemas"]["EmailValidacio"] | null;
            /** Suppression */
            suppression: {
                [key: string]: number;
            };
            /** Labels */
            labels: {
                [key: string]: number;
            };
            /** Unlinked Sources */
            unlinked_sources: number;
            /** Outreach */
            outreach: {
                [key: string]: number;
            };
            /** Next Steps */
            next_steps: components["schemas"]["KovetkezoLepes"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            db: components["schemas"]["DbAllapot"];
            sender_dir: components["schemas"]["SenderDirAllapot"];
            migraciok: components["schemas"]["MigraciokAllapot"];
            /** Verzio */
            verzio: string;
        };
        /** JobCatalogItem */
        JobCatalogItem: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
            /** Magyarazat */
            magyarazat: string;
            /** Parancs */
            parancs: string;
            /** Parameterek */
            parameterek: components["schemas"]["JobParamMeta"][];
            koltseg: components["schemas"]["JobKoltseg"];
        };
        /** JobCatalogResponse */
        JobCatalogResponse: {
            /** Items */
            items: components["schemas"]["JobCatalogItem"][];
        };
        /** JobCurrentResponse */
        JobCurrentResponse: {
            job: components["schemas"]["JobItem"] | null;
        };
        /** JobHistoryResponse */
        JobHistoryResponse: {
            /** Items */
            items: components["schemas"]["JobItem"][];
        };
        /** JobItem */
        JobItem: {
            /** Id */
            id: string;
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
            /** Parancs */
            parancs: string;
            /** Fut */
            fut: boolean;
            /** Allapot */
            allapot: string;
            /** Allapot Cimke */
            allapot_cimke: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Seconds */
            seconds: number | null;
            /** Exit Code */
            exit_code: number | null;
        };
        /**
         * JobKoltseg
         * @description A becsult koltseg NYERSANYAGA, nem egy kesz szam.
         *
         *     Az Apify-resz szorzas (egysegar x darab), tehat a felulet ki tudja
         *     szamolni, amint a felhasznalo allit a kereten. Az AI-resz elore NEM
         *     becsulheto (tokenenkent szamlazodik) -- ilyenkor `ai_tokenenkent=True`,
         *     es a felulet ezt irja ki, nem egy kitalalt osszeget (WEBUI-TERV.md F6).
         */
        JobKoltseg: {
            /** Fizetos */
            fizetos: boolean;
            /** Apify Egysegar Usd */
            apify_egysegar_usd: number | null;
            /** Apify Fix Darab */
            apify_fix_darab: number | null;
            /** Apify Darab Parametere */
            apify_darab_parametere: string | null;
            /** Ai Tokenenkent */
            ai_tokenenkent: boolean;
            /** Magyarazat */
            magyarazat: string;
        };
        /** JobOutputResponse */
        JobOutputResponse: {
            job: components["schemas"]["JobItem"];
            /** Lines */
            lines: string[];
            /** Cursor */
            cursor: number;
        };
        /**
         * JobParamMeta
         * @description Egy allithato keret. Az `alap` a CLI sajat argparse-abol jon
         *     (webui/api/jobs.py `_alap_ertekek`), nem kezi masolatbol.
         */
        JobParamMeta: {
            /** Nev */
            nev: string;
            /** Flag */
            flag: string;
            /** Cimke */
            cimke: string;
            /** Alap */
            alap: number;
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** JobResponse */
        JobResponse: {
            job: components["schemas"]["JobItem"];
        };
        /** JobStartBody */
        JobStartBody: {
            /** Kulcs */
            kulcs: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number;
            };
        };
        /** KampanyMeta */
        KampanyMeta: {
            /** Kulcs */
            kulcs: string;
            /** Jovahagyott */
            jovahagyott: boolean;
        };
        /** KovetkezoLepes */
        KovetkezoLepes: {
            /** Status */
            status: string;
            /** Count */
            count: number;
            /** Action */
            action: string;
        };
        /** LogResponse */
        LogResponse: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Lines */
            lines: string[];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Statuszok */
            statuszok: components["schemas"]["StatuszMeta"][];
            /** Kampanyok */
            kampanyok: components["schemas"]["KampanyMeta"][];
            /** Engine Ek */
            engine_ek: components["schemas"]["EngineMeta"][];
            /** Suppression Okok */
            suppression_okok: string[];
            /** Valasz Osztalyok */
            valasz_osztalyok: components["schemas"]["ValaszOsztalyMeta"][];
            /** Cimkek */
            cimkek: string[];
            /** Kuszobok */
            kuszobok: {
                [key: string]: number;
            };
        };
        /** MigraciokAllapot */
        MigraciokAllapot: {
            /** Alkalmazott */
            alkalmazott: number;
            /** Utolso */
            utolso: string | null;
        };
        /** ModellKoltseg */
        ModellKoltseg: {
            /** Hivasok */
            hivasok: number;
            /** Be */
            be: number;
            /** Ki */
            ki: number;
            /** Usd */
            usd: number;
        };
        /**
         * RejectBody
         * @description A `reason` a /api/meta `suppression_okok` listajabol valaszthato a
         *     fronton -- ez a mezo itt csak nyers string, az ervenyesseget a DB CHECK
         *     constraint es a leadgen/review.py donti el, nem a webui.
         */
        RejectBody: {
            /**
             * Reason
             * @default manual_block
             */
            reason: string;
        };
        /** RepliesResponse */
        RepliesResponse: {
            /** Items */
            items: components["schemas"]["ReplyItem"][];
            /** Total */
            total: number;
        };
        /** ReplyItem */
        ReplyItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Received At */
            received_at: string | null;
            /** Subject */
            subject: string | null;
            /** Classification */
            classification: string | null;
            /** Confidence */
            confidence: number | null;
            /** Rationale */
            rationale: string | null;
            /** Error */
            error: string | null;
            /** Classified At */
            classified_at: string | null;
            /** Company Name */
            company_name: string | null;
            /** Normalized Domain */
            normalized_domain: string | null;
        };
        /**
         * ReviewActionResponse
         * @description A jovahagyas/elutasitas eredmenye -- ugyanaz az uj allapot, amit a
         *     CLI is kiirna (leadgen/review.py, egy forras a ket hivonak).
         */
        ReviewActionResponse: {
            /** Uj Status */
            uj_status: string;
        };
        /** RiasztasBlokk */
        RiasztasBlokk: {
            /** Ok */
            ok: boolean;
            /** Aktiv */
            aktiv: components["schemas"]["RiasztasSor"][];
            /** Error */
            error: string | null;
        };
        /** RiasztasSor */
        RiasztasSor: {
            /** Kulcs */
            kulcs: string;
            /** Tipus */
            tipus: string;
            /** Uzenet */
            uzenet: string;
            /** First Seen */
            first_seen?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /** Last Notified */
            last_notified?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** RunsResponse */
        RunsResponse: {
            /** Items */
            items: components["schemas"]["SourceRunItem"][];
            /** Total */
            total: number;
        };
        /** ScheduleStatusResponse */
        ScheduleStatusResponse: {
            /** Installed */
            installed: boolean;
            /** Loaded */
            loaded: boolean;
            /** Launchctl Lines */
            launchctl_lines: string[];
            /** Start Time */
            start_time: string;
            /** Log Path */
            log_path: string;
            /** Log Last Written */
            log_last_written: string | null;
            /** Log Last Lines */
            log_last_lines: string[];
        };
        /**
         * SendLevel
         * @description Egy levele a mai tervnek, TELJES torzzsel -- nem az elso 400 karakter
         *     (WEBUI-TERV.md F7). A `fok` a `sender._stage_of` szerinti szekvencia-fok
         *     (cold / follow_up_1 / follow_up_2), leadenkent kulon.
         */
        SendLevel: {
            /** Cimzett */
            cimzett: string;
            /** Ceg */
            ceg: string;
            /** Fok */
            fok: string;
            /** Targy */
            targy: string;
            /** Torzs */
            torzs: string;
        };
        /**
         * SendLiveBody
         * @description A `/api/send/preview`-tol kapott token. Enelkul nincs eles kuldes.
         */
        SendLiveBody: {
            /** Token */
            token: string;
        };
        /** SendPreviewResponse */
        SendPreviewResponse: {
            /** Token */
            token: string;
            /**
             * Lejar
             * Format: date-time
             */
            lejar: string;
            /** Levelek */
            levelek: components["schemas"]["SendLevel"][];
            /** Mai Keret */
            mai_keret: number;
            /** Terv Meret */
            terv_meret: number;
            /** Ablak Nyitva */
            ablak_nyitva: boolean;
            /** Ablak Ok */
            ablak_ok: string;
        };
        /** SendSampleBody */
        SendSampleBody: {
            /** Cim */
            cim: string;
            /**
             * Limit
             * @default 1
             */
            limit: number;
            /**
             * Fok
             * @default cold
             */
            fok: string;
        };
        /**
         * SendSampleResponse
         * @description A `preview.py --send-to` kimenete. A valodi cimzettek nem kapnak
         *     semmit, es a `sent.csv` sem valtozik.
         */
        SendSampleResponse: {
            /** Ok */
            ok: boolean;
            /** Sorok */
            sorok: string[];
            /** Error */
            error: string | null;
        };
        /**
         * SenderAllapot
         * @description A kuldo sajat szamai. `ok=False` -> nem tudtuk megkerdezni, es akkor a
         *     tobbi mezo nulla -- NEM talalt szam, hanem "nem tudjuk" (report.py).
         */
        SenderAllapot: {
            /** Ok */
            ok: boolean;
            /** Cap */
            cap: number;
            /** Sent Today */
            sent_today: number;
            /** Remaining */
            remaining: number;
            /** Leads Rows */
            leads_rows: number;
            /** Bounces Today */
            bounces_today: number;
            /** Rejects Today */
            rejects_today: number;
            /** Error */
            error: string | null;
        };
        /** SenderDirAllapot */
        SenderDirAllapot: {
            /** Ok */
            ok: boolean;
            /** Ut */
            ut: string;
        };
        /** SourceRunItem */
        SourceRunItem: {
            /** Engine Key */
            engine_key: string;
            /** Actor */
            actor: string;
            /** Term */
            term: string | null;
            /** Location */
            location: string | null;
            /** Results */
            results: number | null;
            /** New Companies */
            new_companies: number | null;
            /** Run At */
            run_at: string | null;
        };
        /** StatuszMeta */
        StatuszMeta: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
            /** Sorrend */
            sorrend: number;
        };
        /** SuppressedCompanyItem */
        SuppressedCompanyItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Domain */
            normalized_domain: string | null;
            /** Company Name */
            company_name: string | null;
            /** Status Note */
            status_note: string | null;
            /** Title */
            title: string | null;
        };
        /** SuppressedListResponse */
        SuppressedListResponse: {
            /** Items */
            items: components["schemas"]["SuppressedCompanyItem"][];
        };
        /** ValaszOsztalyMeta */
        ValaszOsztalyMeta: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    report_daily_api_report_daily_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResponse"];
                };
            };
        };
    };
    report_funnel_api_report_funnel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelResponse"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: {
                status?: string | null;
                campaign?: string | null;
                engine?: string | null;
                economic_value?: string | null;
                label?: string | null;
                q?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_detail_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_replies_api_replies_get: {
        parameters: {
            query?: {
                classification?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepliesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    costs_api_costs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostsResponse"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_status_api_schedule_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleStatusResponse"];
                };
            };
        };
    };
    log_tail_api_logs__nev__get: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                nev: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_approve_api_review__company_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_reject_api_review__company_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_suppressed_api_review_suppressed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressedListResponse"];
                };
            };
        };
    };
    financials_worklist_api_financials_worklist_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    financials_import_api_financials_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_financials_import_api_financials_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialsImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_financials_save_api_companies__company_id__financials_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyFinancialsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialsSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_catalog_api_jobs_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCatalogResponse"];
                };
            };
        };
    };
    job_current_api_jobs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCurrentResponse"];
                };
            };
        };
    };
    job_history_api_jobs_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_start_api_jobs_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobStartBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_cancel_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_output_api_jobs__job_id__get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOutputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_api_jobs__job_id__stream_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_preview_api_send_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendPreviewResponse"];
                };
            };
        };
    };
    send_live_api_send_live_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendLiveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_sample_api_send_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendSampleBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendSampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
