/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Daily */
        get: operations["report_daily_api_report_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Funnel */
        get: operations["report_funnel_api_report_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Detail */
        get: operations["company_detail_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Replies */
        get: operations["list_replies_api_replies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Costs */
        get: operations["costs_api_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedule Status */
        get: operations["schedule_status_api_schedule_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{nev}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Tail */
        get: operations["log_tail_api_logs__nev__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertsResponse */
        AlertsResponse: {
            /** Aktiv */
            aktiv: components["schemas"]["RiasztasSor"][];
            /** Lezart */
            lezart: components["schemas"]["RiasztasSor"][];
        };
        /**
         * CompanyDetailResponse
         * @description A reszletes nezet. A sorok `select *`-gal jonnek (lasd a modul
         *     docstringjet), ezert a BURKOLO tipusos, a sorok mezoi nem.
         */
        CompanyDetailResponse: {
            /** Company */
            company: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Contacts */
            contacts: {
                [key: string]: unknown;
            }[];
            /** Opportunity Angles */
            opportunity_angles: {
                [key: string]: unknown;
            }[];
            /** Company Labels */
            company_labels: {
                [key: string]: unknown;
            }[];
            /** Outreach */
            outreach: {
                [key: string]: unknown;
            }[];
            /** Suppression */
            suppression: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CompanyListItem
         * @description A lista-nezet oszlopai. Ezt a lekerdezes NEV SZERINT valasztja ki
         *     (nem `select *`), ezert itt teljes a modell.
         */
        CompanyListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Name */
            company_name: string | null;
            /** Normalized Domain */
            normalized_domain: string | null;
            /** Status */
            status: string;
            /** Campaign */
            campaign: string | null;
            /** Economic Value */
            economic_value: string | null;
            /** Signal Score */
            signal_score: number | null;
            /** City */
            city: string | null;
            /** Industry */
            industry: string | null;
            /** Best Offer */
            best_offer: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Email */
            email: string | null;
        };
        /** CompanyListResponse */
        CompanyListResponse: {
            /** Items */
            items: components["schemas"]["CompanyListItem"][];
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** CostsResponse */
        CostsResponse: {
            /** Has Data */
            has_data: boolean;
            /** By Model */
            by_model: {
                [key: string]: components["schemas"]["ModellKoltseg"];
            };
            /** Total Usd */
            total_usd: number;
            /** First Ts */
            first_ts: string | null;
            /** Last Ts */
            last_ts: string | null;
        };
        /** DailyResponse */
        DailyResponse: {
            riasztasok: components["schemas"]["RiasztasBlokk"];
            sender: components["schemas"]["SenderAllapot"];
            /** Queued */
            queued: number;
            /** Ready */
            ready: number;
            /** Replied */
            replied: number;
            /** Review */
            review: number;
            /** Days Of Backlog */
            days_of_backlog: number | null;
        };
        /** DbAllapot */
        DbAllapot: {
            /** Ok */
            ok: boolean;
            /** Tablak */
            tablak: number;
        };
        /** EmailValidacio */
        EmailValidacio: {
            /** Mode */
            mode: string;
            /** Summary */
            summary: string;
        };
        /** EngineMeta */
        EngineMeta: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
            /** Aktiv */
            aktiv: boolean;
        };
        /** FunnelResponse */
        FunnelResponse: {
            /** Companies Total */
            companies_total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Unknown Status */
            unknown_status: {
                [key: string]: number;
            };
            /** Contacts */
            contacts: {
                [key: string]: number;
            };
            email_validation: components["schemas"]["EmailValidacio"] | null;
            /** Suppression */
            suppression: {
                [key: string]: number;
            };
            /** Labels */
            labels: {
                [key: string]: number;
            };
            /** Unlinked Sources */
            unlinked_sources: number;
            /** Outreach */
            outreach: {
                [key: string]: number;
            };
            /** Next Steps */
            next_steps: components["schemas"]["KovetkezoLepes"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            db: components["schemas"]["DbAllapot"];
            sender_dir: components["schemas"]["SenderDirAllapot"];
            migraciok: components["schemas"]["MigraciokAllapot"];
            /** Verzio */
            verzio: string;
        };
        /** KampanyMeta */
        KampanyMeta: {
            /** Kulcs */
            kulcs: string;
            /** Jovahagyott */
            jovahagyott: boolean;
        };
        /** KovetkezoLepes */
        KovetkezoLepes: {
            /** Status */
            status: string;
            /** Count */
            count: number;
            /** Action */
            action: string;
        };
        /** LogResponse */
        LogResponse: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Lines */
            lines: string[];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Statuszok */
            statuszok: components["schemas"]["StatuszMeta"][];
            /** Kampanyok */
            kampanyok: components["schemas"]["KampanyMeta"][];
            /** Engine Ek */
            engine_ek: components["schemas"]["EngineMeta"][];
            /** Suppression Okok */
            suppression_okok: string[];
            /** Valasz Osztalyok */
            valasz_osztalyok: components["schemas"]["ValaszOsztalyMeta"][];
            /** Cimkek */
            cimkek: string[];
            /** Kuszobok */
            kuszobok: {
                [key: string]: number;
            };
        };
        /** MigraciokAllapot */
        MigraciokAllapot: {
            /** Alkalmazott */
            alkalmazott: number;
            /** Utolso */
            utolso: string | null;
        };
        /** ModellKoltseg */
        ModellKoltseg: {
            /** Hivasok */
            hivasok: number;
            /** Be */
            be: number;
            /** Ki */
            ki: number;
            /** Usd */
            usd: number;
        };
        /** RepliesResponse */
        RepliesResponse: {
            /** Items */
            items: components["schemas"]["ReplyItem"][];
            /** Total */
            total: number;
        };
        /** ReplyItem */
        ReplyItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Received At */
            received_at: string | null;
            /** Subject */
            subject: string | null;
            /** Classification */
            classification: string | null;
            /** Confidence */
            confidence: number | null;
            /** Rationale */
            rationale: string | null;
            /** Error */
            error: string | null;
            /** Classified At */
            classified_at: string | null;
            /** Company Name */
            company_name: string | null;
            /** Normalized Domain */
            normalized_domain: string | null;
        };
        /** RiasztasBlokk */
        RiasztasBlokk: {
            /** Ok */
            ok: boolean;
            /** Aktiv */
            aktiv: components["schemas"]["RiasztasSor"][];
            /** Error */
            error: string | null;
        };
        /** RiasztasSor */
        RiasztasSor: {
            /** Kulcs */
            kulcs: string;
            /** Tipus */
            tipus: string;
            /** Uzenet */
            uzenet: string;
            /** First Seen */
            first_seen?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /** Last Notified */
            last_notified?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** RunsResponse */
        RunsResponse: {
            /** Items */
            items: components["schemas"]["SourceRunItem"][];
            /** Total */
            total: number;
        };
        /** ScheduleStatusResponse */
        ScheduleStatusResponse: {
            /** Installed */
            installed: boolean;
            /** Loaded */
            loaded: boolean;
            /** Launchctl Lines */
            launchctl_lines: string[];
            /** Start Time */
            start_time: string;
            /** Log Path */
            log_path: string;
            /** Log Last Written */
            log_last_written: string | null;
            /** Log Last Lines */
            log_last_lines: string[];
        };
        /**
         * SenderAllapot
         * @description A kuldo sajat szamai. `ok=False` -> nem tudtuk megkerdezni, es akkor a
         *     tobbi mezo nulla -- NEM talalt szam, hanem "nem tudjuk" (report.py).
         */
        SenderAllapot: {
            /** Ok */
            ok: boolean;
            /** Cap */
            cap: number;
            /** Sent Today */
            sent_today: number;
            /** Remaining */
            remaining: number;
            /** Leads Rows */
            leads_rows: number;
            /** Bounces Today */
            bounces_today: number;
            /** Rejects Today */
            rejects_today: number;
            /** Error */
            error: string | null;
        };
        /** SenderDirAllapot */
        SenderDirAllapot: {
            /** Ok */
            ok: boolean;
            /** Ut */
            ut: string;
        };
        /** SourceRunItem */
        SourceRunItem: {
            /** Engine Key */
            engine_key: string;
            /** Actor */
            actor: string;
            /** Term */
            term: string | null;
            /** Location */
            location: string | null;
            /** Results */
            results: number | null;
            /** New Companies */
            new_companies: number | null;
            /** Run At */
            run_at: string | null;
        };
        /** StatuszMeta */
        StatuszMeta: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
            /** Sorrend */
            sorrend: number;
        };
        /** ValaszOsztalyMeta */
        ValaszOsztalyMeta: {
            /** Kulcs */
            kulcs: string;
            /** Cimke */
            cimke: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    report_daily_api_report_daily_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResponse"];
                };
            };
        };
    };
    report_funnel_api_report_funnel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelResponse"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: {
                status?: string | null;
                campaign?: string | null;
                engine?: string | null;
                economic_value?: string | null;
                label?: string | null;
                q?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_detail_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_replies_api_replies_get: {
        parameters: {
            query?: {
                classification?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepliesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    costs_api_costs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostsResponse"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_status_api_schedule_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleStatusResponse"];
                };
            };
        };
    };
    log_tail_api_logs__nev__get: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                nev: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
